version: "2"
use_cases:
- name: default
  sections:
  - name: Config
    groups:
    - name: terraform
      technologies:
      - terraform
      vars:
      - widget: text_area
        required: true
        default: eastus
        type: string
        key: azurerm_resource_group__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_location
        name: azurerm_resource_group__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_location
      - widget: text_area
        required: true
        default: terraform
        type: string
        key: azurerm_resource_group__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_name
        name: azurerm_resource_group__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_name
      - widget: text_area
        required: true
        default: base
        type: string
        key: azurerm_resource_group__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_tc_category
        name: azurerm_resource_group__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_tc_category
