resource "azurerm_virtual_network" "_subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_rgp_providers_microsoft_network_virtualnetworks_vnet_south_india" {
  address_space       = var.azurerm_virtual_network__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_rgp_providers_microsoft_network_virtualnetworks_vnet_south_india_address_space
  location            = var.azurerm_virtual_network__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_rgp_providers_microsoft_network_virtualnetworks_vnet_south_india_location
  name                = var.azurerm_virtual_network__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_rgp_providers_microsoft_network_virtualnetworks_vnet_south_india_name
  resource_group_name = var.azurerm_virtual_network__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_rgp_providers_microsoft_network_virtualnetworks_vnet_south_india_resource_group_name
  subnet {
    address_prefix = var.azurerm_virtual_network__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_rgp_providers_microsoft_network_virtualnetworks_vnet_south_india_subnet_address_prefix
    name           = var.azurerm_virtual_network__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_rgp_providers_microsoft_network_virtualnetworks_vnet_south_india_subnet_name
  }

  subnet {
    address_prefix = var.azurerm_virtual_network__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_rgp_providers_microsoft_network_virtualnetworks_vnet_south_india_subnet_address_prefix
    name           = var.azurerm_virtual_network__subscriptions_97d20ca8_3e22_470f_8d26_e3c1fd97ca6e_resourcegroups_terraform_rgp_providers_microsoft_network_virtualnetworks_vnet_south_india_subnet_name
  }

}

